name: iruka_quiz
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3
  html_character_entities: ^1.0.0+1
  meta: ^1.7.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
