name: iruka_quiz
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  enum_to_string: ^1.0.14
  equatable: ^1.2.6
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.4
  html_character_entities: ^0.1.2+4
  meta: ^1.2.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
